INFO:werkzeug: * Running on http://127.0.0.206:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:32:48] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:32:51] "[37mPOST / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:33:10] "[37mPOST / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.206:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:34:11] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:34:19] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.206:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:34:51] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:34:56] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.206:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:35:22] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:35:24] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:35:45] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:35:45] "[37mGET /static/analytics.js HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:35:45] "[37mGET /static/utils.js HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:35:45] "[37mGET /static/Chart.min.js HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:35:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.207:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Data\Test\2020.12.24 Gorila BackEnd Test\FlaskApp\App\app.py", line 75, in main_page
    return render_template('line_chart2.html', legend=legend, legend2=legend2, downBtn=true)
NameError: name 'true' is not defined
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:38:08] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.207:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:38:47] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jan/2021 04:38:50] "[37mPOST / HTTP/1.1[0m" 200 -
