A warning occurred (42 apples)
A warning occurred (42 apples)
A warning occurred (42 apples)
A warning occurred (42 apples)
A warning occurred (42 apples)
A warning occurred (42 apples)
A warning occurred (42 apples)
Exception on / [GET]
Traceback (most recent call last):
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Data\Test\2020.12.24 Gorila BackEnd Test\FlaskApp\App\app.py", line 36, in main_page
    app.logger.info('Main Page Opened at: ' + datetime.now())
TypeError: can only concatenate str (not "datetime.datetime") to str
Main Page Opened at: 2021-01-02 23:16:56.528403
Main Page Opened at: 2021-01-02 23:17:33.303403
Log Info [2021-01-02 23:19:14.309551]: Main Page Opened
LogInfo[2021-01-02 23:21:25.528716]: Main Page Opened
LogInfo[2021-01-02 23:21:34.293395]: Main Page Opened
LogInfo[2021-01-02 23:21:48.658159]: results_2021.01.02_23.21.34.csvDownloaded
LogInfo[2021-01-02 23:23:04.447959]: Main Page Opened
LogInfo[2021-01-02 23:23:10.802039]: Main Page Opened
LogInfo[2021-01-02 23:23:15.278040]: File: results_2021.01.02_23.23.10.csv Downloaded
LogInfo[2021-01-02 23:25:29.856694]: Main Page Opened
Exception on / [GET]
Traceback (most recent call last):
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Data\Test\2020.12.24 Gorila BackEnd Test\FlaskApp\App\app.py", line 86, in main_page
    return render_template('line_chart2.html', legend=legend, legend2=legend2, downBtn='true')
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\Data\Test\2020.12.24 Gorila BackEnd Test\FlaskApp\App\templates\line_chart2.html", line 148, in top-level template code
    <p><form action="{{ url_for('log_download', filename=logFile) }}">
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "d:\users\autaza\appdata\local\programs\python\python38\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'log_download' with values ['filename']. Did you forget to specify values ['logFile']?
LogInfo[2021-01-02 23:26:21.191382]: Main Page Opened
LogInfo[2021-01-02 23:31:01.797333]: Main Page Opened
LogInfo[2021-01-02 23:32:42.311183]: Main Page Opened
LogInfo[2021-01-02 23:33:06.719450]: Main Page Opened
LogInfo[2021-01-02 23:33:09.005463]: File: results_2021.01.02_23.33.06.csv Downloaded
LogInfo[2021-01-02 23:33:30.771860]: File: cdbCalculator.log Downloaded
LogInfo[2021-01-02 23:35:40.540217]: Main Page Opened
LogInfo[2021-01-02 23:35:44.904586]: Main Page Opened
LogInfo[2021-01-02 23:35:57.630810]: Main Page Opened
LogInfo[2021-01-02 23:39:39.770278]: Main Page Opened
LogInfo[2021-01-02 23:41:40.294932]: Main Page Opened
LogInfo[2021-01-02 23:42:30.309050]: Main Page Opened
LogInfo[2021-01-02 23:42:41.271377]: Main Page Opened
LogInfo[2021-01-02 23:42:46.806376]: File: results_2021.01.02_23.42.41.csv Downloaded
LogInfo[2021-01-02 23:46:10.079642]: Main Page Opened
LogInfo[2021-01-02 23:47:13.511919]: Main Page Opened
LogInfo[2021-01-02 23:47:21.560434]: Main Page Opened
LogInfo[2021-01-02 23:47:41.013316]: Main Page Opened
LogInfo[2021-01-02 23:47:45.779385]: File: cdbCalculator.log Downloaded
LogInfo[2021-01-02 23:49:04.301517]: Main Page Opened
LogInfo[2021-01-02 23:49:09.294071]: File: cdbCalculator.log Downloaded
LogInfo[2021-01-02 23:51:30.323219]: Main Page Opened
LogInfo[2021-01-02 23:53:29.804265]: Main Page Opened
LogInfo[2021-01-02 23:53:31.396266]: File: cdbCalculator.log Downloaded
LogInfo[2021-01-02 23:54:09.284790]: Main Page Opened
LogInfo[2021-01-03 00:05:10.794811]: Main Page Opened
LogInfo[2021-01-03 00:05:13.584814]: File: cdbCalculator.log Downloaded
LogInfo[2021-01-03 00:05:18.466851]: Main Page Opened
LogInfo[2021-01-03 00:05:19.804850]: File: results_2021.01.03_00.05.18.csv Downloaded
LogInfo[2021-01-03 00:07:19.863578]: Main Page Opened
LogInfo[2021-01-03 00:07:24.303487]: Main Page Opened
LogInfo[2021-01-03 00:07:30.140152]: File: results.csv Downloaded
